# Generated by Django 6.0.6 on 2026-06-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254)),
                ("comment", models.TextField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("notification_failed", "Notification failed"),
                        ],
                        default="received",
                        max_length=32,
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        default="neutral",
                        max_length=16,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("job_offer", "Job offer"),
                            ("consultation", "Consultation"),
                            ("feedback", "Feedback"),
                            ("question", "Question"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("ai_reply", models.TextField(blank=True)),
                ("ai_provider", models.CharField(blank=True, max_length=80)),
                ("ai_fallback_reason", models.CharField(blank=True, max_length=255)),
                ("owner_email_sent", models.BooleanField(default=False)),
                ("user_email_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="contact_status_created_idx",
                    ),
                    models.Index(
                        fields=["request_type", "-created_at"],
                        name="contact_type_created_idx",
                    ),
                ],
            },
        ),
    ]
